import type { Metadata } from "next";
import { ThemeProvider } from 'next-themes';
import { Onest } from 'next/font/google';
import "./globals.css";

const onest = Onest({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-gray-100 dark:bg-dark-secondary min-h-screen flex flex-col ${onest.className}`}
      >
        <ThemeProvider disableTransitionOnChange>
          <div className="isolate flex flex-col flex-1">
            {children}
          </div>
        </ThemeProvider>

      </body>
    </html>
  );
}
